# Generated by Django 4.2.28 on 2026-03-02 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DEACTIVATE', 'Deactivate Account'), ('DELETE', 'Delete Account'), ('ACTIVATE', 'Activate Account')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(help_text='Staff member who created this request.', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_actions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who approved or rejected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_actions', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='banking.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
